### ISSUE TITLE
关于“刷洞”部分的建议

### ISSUE THREAD

**Issue by CodingZn** [bwnotfound/pypvzol#2]
打暗洞、个人洞和公共洞时，似乎只有勾选“没炮灰才停止挑战”才可以重复刷洞；勾选之后，在所有洞都已经没法打（需要时之沙冷却）仍在不停的查看洞口。这边或许可以判断一下如果某时刻没有洞可以刷了就退出来进行其他的操作（也可以做成选项，是否无限轮询）。
以及可以把挑战宝石副本和刷洞分开来。
刷副本和宝石副本的时候感觉可以设置成，指定每个副本要刷的次数，然后采用刷完一个洞再刷另一个的机制（类似老助手一样）。

**Comment by CodingZn** [comment]
以及，在不停查看洞口的时候如果点暂停，有概率卡死导致只能强制关闭程序

**Comment by bwnotfound** [comment]
指定刷洞次数实际上是不方便的，因为在有一键刷洞的前提下，助手刷洞只有带少数植物等级和稳定打洞才会用到。没有洞就停止可以考虑做成选项，之后会加入。

**Comment by bwnotfound** [comment]
关于助手机制问题，可以加qq群692034778询问

**Comment by bwnotfound** [comment]
你截图一下你的刷洞设置，我试试复现

**Comment by CodingZn** [comment]
![PcSRC_20231219_174647](https://github.com/bwnotfound/pypvzol/assets/114711191/d3788455-7326-4d83-be00-8827278a9ff2)
大概在开了很久的情况下，卡死的概率更大。
点了暂停有可能不卡死，但是之后再点开始也有概率卡死。

**Comment by bwnotfound** [comment]
出战植物得确保是有血的，你跳过了仓库同时没有给植物回血，所以挑战不了。建议打开植物回血和关闭仓库加速。其它问题可以进群问

**Comment by CodingZn** [comment]
> 出战植物得确保是有血的，你跳过了仓库同时没有给植物回血，所以挑战不了。建议打开植物回血和关闭仓库加速。其它问题可以进群问

似乎卡死并不是因为植物没血，我刚刚给主力和炮灰都上了几亿的血量、百万的闪避和护甲 去刷洞，然而还是出现了这种情况，但是主力和炮灰还都是满血
